version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    volumes:
      - ./backend:/app

networks:
  app_network:
    driver: bridge
